export IDF_PATH := ./esp-idf
PROJECT_NAME := hatchtrack-peep-fw

EXTRA_COMPONENT_DIRS := \
  ble \
  bme680 \
  hal \
  iot \
  icm20602 \
  peep \
  OSAL \
  wifi

include $(IDF_PATH)/make/project.mk

CFLAGS += -DPEEP_TEST_STATE_MEASURE_CONFIG
