/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Thu Jun 21 21:44:48 2018. */

#include "peep.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Version_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Version, major_version, major_version, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, Version, minor_version, major_version, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, Version, patch_version, minor_version, 0),
    PB_LAST_FIELD
};

const pb_field_t HatchConfiguration_fields[11] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, HatchConfiguration, user_uuid, user_uuid, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, HatchConfiguration, hatch_uuid, user_uuid, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, HatchConfiguration, egg_type, hatch_uuid, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, HatchConfiguration, egg_count, egg_type, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, HatchConfiguration, duration, egg_count, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, HatchConfiguration, notifications_enabled, duration, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, HatchConfiguration, temperature_max, notifications_enabled, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, HatchConfiguration, temperature_min, temperature_max, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, HatchConfiguration, humididty_max, temperature_min, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, HatchConfiguration, humidity_min, humididty_max, 0),
    PB_LAST_FIELD
};

const pb_field_t ClientCommandConfigureHatch_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, ClientCommandConfigureHatch, configuration, configuration, &HatchConfiguration_fields),
    PB_LAST_FIELD
};

const pb_field_t ClientCommand_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ClientCommand, type, type, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, ClientCommand, configure_hatch, type, &ClientCommandConfigureHatch_fields),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, ClientCommand, payload, configure_hatch, 0),
    PB_LAST_FIELD
};

const pb_field_t ClientQuery_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ClientQuery, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t ClientMessage_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ClientMessage, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ClientMessage, id, type, 0),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, ClientMessage, command, id, &ClientCommand_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, ClientMessage, query, command, &ClientQuery_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceCommandResult_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, DeviceCommandResult, type, type, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, DeviceCommandResult, result, type, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceInquryResult_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, DeviceInquryResult, type, type, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, DeviceInquryResult, result, type, 0),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, DeviceInquryResult, version, result, &Version_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, DeviceInquryResult, hatch_configuration, version, &HatchConfiguration_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceMessage_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, DeviceMessage, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, DeviceMessage, id, type, 0),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, DeviceMessage, command_result, id, &DeviceCommandResult_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, DeviceMessage, query_result, command_result, &DeviceInquryResult_fields),
    PB_LAST_FIELD
};










/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ClientCommandConfigureHatch, configuration) < 65536 && pb_membersize(ClientCommand, configure_hatch) < 65536 && pb_membersize(ClientCommand, payload) < 65536 && pb_membersize(ClientMessage, command) < 65536 && pb_membersize(ClientMessage, query) < 65536 && pb_membersize(DeviceInquryResult, version) < 65536 && pb_membersize(DeviceInquryResult, hatch_configuration) < 65536 && pb_membersize(DeviceMessage, command_result) < 65536 && pb_membersize(DeviceMessage, query_result) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Version_HatchConfiguration_ClientCommandConfigureHatch_ClientCommand_ClientQuery_ClientMessage_DeviceCommandResult_DeviceInquryResult_DeviceMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for ClientCommand.payload is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
